server:
  port: 8086

spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always

  config:
      import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

#enable and expose all management endpoints related to actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"