##Start with a base image containing Java runtime
##FROM openjdk:17-jdk-slim
#FROM eclipse-temurin:17-jdk-jammy
##information around who maintains the image
#MAINTAINER eazybytes.com
#
##add application jar to the image
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#
#
##same zy akeny brun mn terminal java -jar target/accounts-0.01-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]